# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_coldstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldstorage',
            name='empty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='coldstorage',
            name='space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coldstorage',
            name='yieldType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
